import type { Metadata } from "next";
import Header from './components/Header';
import Footer from './components/Footer';
import './styles/default.css';
import './styles/header.css';
import './styles/main.css';
import './styles/footer.css';
import 'reset-css';
import '@fontsource-variable/antonio';
import '@fontsource/spartan';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  links,
}: Readonly<{
  children: React.ReactNode;
  links: Array<{ id: string; name: string }>;
}>) {

  return (
    <html lang="en">
      <body>
        <Header links={links} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
